name: insta_album_new
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dio: ^2.1.7
  progress_dialog: ^1.2.0
  shared_preferences: ^0.5.3+4
  firebase_messaging: ^5.1.8
  intl: ^0.16.0
  fluttertoast: ^3.1.3
  path_provider: ^1.2.0
  esys_flutter_share: ^1.0.2
  flutter_staggered_grid_view: ^0.3.0
  flutter_local_notifications: ^0.8.4
  transparent_image: ^1.0.0
  flutter_speed_dial: ^1.2.1
  contacts_service: ^0.0.8
  permission_handler: ^4.0.0
  url_launcher: ^5.1.6
  flutter_cupertino_date_picker: ^1.0.12
  flutter_native_image: ^0.0.4
  network_to_file_image: ^2.1.4
  share: ^0.6.3+4
  photo_view: ^0.9.0
  pin_code_text_field: ^1.5.0
  image_gallery_saver: ^1.2.2
  gallery_saver: ^1.0.7
  carousel_pro: ^1.0.0
  #audioplayers: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/icon_camera.png
    - images/icon_photoframe1.png
    - images/icon_login.png
    - images/icon_logo.png
    - images/om2.png
    - images/icon_cameranew.png
    - images/icon_selected.png
    - images/icon_pending.png
    - images/icon_allimages.png
    - images/icon_maximize.png
    - images/bg.jpeg
    - images/om.png
    - images/earth.png
    - images/twitter.png
    - images/linkedin.png
    - images/instagram.png
    - images/facebook.png
    - images/insta_placeholder.png
    - images/no_data.png
    - images/man.png
    - images/whatsapp.png
    - assets/loading.gif
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
